// src/components/content/Readme.tsx
export default function Readme() {
  return (
    <section>
      <h1>README</h1>
      <p>Welcome to wander-lang.dev!</p>
      <p>This website is an experimental interface for working with the Wander language.</p>
      <p>Learn more about Wander and Ligature at <a href="https://ligature.dev">ligature.dev</a>.</p>
      <p>Status: pre-alpha and not really usable yet beyond proof of concept but feel free to play around</p>
    </section>
  );
}

// src/components/content/Readme.svelte
<script lang="ts">
</script>

<section>
  <h1>README</h1>
  <p>Welcome to wander-lang.dev!</p>
  <p>This website is an experimental interface for working with the Wander language.</p>
  <p>Learn more about Wander and Ligature at <a href="https://ligature.dev">ligature.dev</a>.</p>
  <p>Status: pre-alpha and not really usable yet beyond proof of concept but feel free to play around</p>
</section>
